[add-controllers] Добавил контроллеры вещей и пользователей
aKorishev/java-shareit pull request #1
Opened 2024-10-26 06:02 UTC by aKorishev

2024-10-26 09:08 UTC, VadimZharkov commented on src/main/java/ru/practicum/shareit/user/storage/UserStorageInMemory.java
> +        if (!users.containsKey(userId)) {
Можно проще и оптимальней. remove возвращает удаленный из мапы объект, поэтому
```
var user = users.remove(userId);
return Optional.ofNullable(user);
```

2024-10-26 09:12 UTC, VadimZharkov commented on src/main/java/ru/practicum/shareit/user/dto/UserToUpdateDto.java
> +    Optional<String> name;
Здесь лучше без  Optional

2024-10-26 09:16 UTC, VadimZharkov commented on src/main/java/ru/practicum/shareit/user/dto/UserDto.java
> +@Value
`@Value`  служит для описания типов неизменяемых объектов. В джаве с 9-ой версии есть встроенный тип record для таких же целей. Советую к нему присмотреться и использовть вместо `@Value`. Код будет выглядеть современней.

2024-10-26 09:18 UTC, VadimZharkov commented on src/main/java/ru/practicum/shareit/item/dto/ItemToUpdateDto.java
> +    @NotNull Optional<String> name;
Здесь лучше без Optional

2024-10-26 09:21 UTC, VadimZharkov requested changes
Хорошая работа, можно улучшить

2024-10-28 07:43 UTC, aKorishev commented on src/main/java/ru/practicum/shareit/user/dto/UserToUpdateDto.java
> +    Optional<String> name;
Как? Проверять на null?

2024-10-30 11:29 UTC, VadimZharkov commented on src/main/java/ru/practicum/shareit/user/dto/UserToUpdateDto.java
> +    Optional<String> name;
Да
```
@NotNull
Optional<String> name
```
не гарантирует, что значение в Optional не будет null. Сам Optional не будет null,  а значение в нем может быть.

2024-10-30 11:31 UTC, VadimZharkov approved these changes

2024-11-03 07:51 UTC, merged